Add structured deferred imports
dart-lang/dart2js_info pull request #42
Opened 2018-07-12 07:04 UTC by LorenVS

The main motivator for this change is to be able to generate qualified import names from info files. The current deferredFiles map only contains the local import name, which for applications that re-use the same deferred import alias in many different libraries becomes very hard to reason about. I'm taking a stab at this without a ton of research, but I do believe we can generate this format trivially from dart2js.

One potential shortcoming of this approach is I don't believe its possible to build an entire graph of potential output unit dependencies. I'm using a LibraryInfo as the parent of a DeferredImport, which seems sensible. However, that Library could in theory contain two separate loadLibrary() calls for the same deferred import in two separate functions, which are then compiled into two separate OutputUnits. It would be nice to have a mechanism for building the entire OutputUnit dependency graph, but I'm not sure what the most reasonable way to model this is. I'm not certain how reasonable it would be for dart2js to emit information about loadLibrary() calls, and not just about deferred imports. If it did, we should be able to add an info type whose parent is an output unit, and which references a deferred import.

2018-07-12 18:26 UTC, sigmundch requested changes
:) we should make sure to get rid of this TODO once we land this :) 
https://github.com/dart-lang/dart2js_info/blob/master/lib/info.dart#L150

> However, that Library could in theory contain two separate loadLibrary() calls for the same deferred import in two separate functions, which are then compiled into two separate OutputUnits. 

This actually is not allowed by construction: output-units are associated with imports in the program and not with `loadLibrary` calls, that is in part because we sometimes can't tell statically which call to `loadLibrary` guarded an access from a prefix.

Bottom line, we do have an invariant that 1-prefix maps to a single output unit.

Regarding adding support into dart2js, I see two options:
* add the comments like you did here, release a minor version, then eventually change dart2js to support the new format and leave the old one empty (possibly being backwards compatible)
* make a breaking change on this package, but wait to publish it until after we update dart2js so we can put a version constraint on it (that way people using older SDKs don't get the new version). 

I'm partially inclined to the latter, mostly because keeping the package with old field names that are empty doesn't add much value and may simply confuse users.

WDTY?

2018-07-12 18:26 UTC, sigmundch commented on lib/info.dart
>    List<String> imports = <String>[];
add a TODO that we should probably delete this field once we shift to support the new representation.

2018-07-12 18:26 UTC, sigmundch commented on lib/info.dart
> +  final List<DeferredImportInfo> deferredImports = <DeferredImportInfo>[];
eventually if we delete the `imports` below and make a breaking change on this package, we should consider just reusing the old name.

2018-07-12 18:26 UTC, sigmundch commented on lib/info.dart
> +class DeferredImportInfo extends BasicInfo {
I was thinking we don't need to make this a actual `Info` object. Instead, I was inclined to represent this more like we represent `DependencyInfo` on low-level dependencies between elements. In part, that's because I think outputUnit and size don't quite fit. 

I'm inclined to then have an object with a few fields:
* the prefix name
* the actual importUri (although it's not necessary)
* the `LibraryInfo` that contains the import (like the current `parent`, just to make traversals of the graph easier.)

I'm however debating whether we get much value from putting the entire list of "deferredImportInfo" on the top level `AllInfo` - what do you think?

2018-07-12 18:30 UTC, sigmundch commented
One more question: 
> The current deferredFiles map only contains the local import name, which for applications that re-use the same deferred import alias in many different libraries becomes very hard to reason about.

I'm not sure I quite follow - the current deferredFiles is a map from libraryUri to a map from prefix to a list of filenames. Can't a prefix be qualified by the enclosing library `libraryUri#prefix`?

2018-09-26 21:53 UTC, kevmoo commented
Can any progress be made on this?

2018-09-26 22:00 UTC, LorenVS commented
Sorry, I haven't had time to follow up on this change in quite some time. I'll try carve out some time over the next couple of weeks

2021-08-11 09:12 UTC, mit-mit commented
Closing as stale

2021-08-11 09:12 UTC, closed without merging